// Image paths from public/img folder
// In Next.js, images in public folder are accessed via path strings

const images = {
  collection: "/img/collection.png",
  creatorbackground1: "/img/creatorbackground-1.jpeg",
  creatorbackground2: "/img/creatorbackground-2.jpeg",
  creatorbackground3: "/img/creatorbackground-3.jpeg",
  creatorbackground4: "/img/creatorbackground-4.jpg",
  creatorbackground5: "/img/creatorbackground-5.jpg",
  creatorbackground6: "/img/creatorbackground-6.jpg",
  creatorbackground7: "/img/creatorbackground-7.jpg",
  creatorbackground8: "/img/creatorbackground-8.jpg",
  creatorbackground9: "/img/creatorbackground-9.jpg",
  creatorbackground10: "/img/creatorbackground-10.jpg",
  creatorbackground11: "/img/creatorbackground-11.jpg",
  user1: "/img/user-1.png",
  user2: "/img/user-2.png",
  user3: "/img/user-3.png",
  user4: "/img/user-4.png",
  user5: "/img/user-5.png",
  user6: "/img/user-6.png",
  user7: "/img/user-7.png",
  user8: "/img/user-8.png",
  user9: "/img/user-9.png",
  user10: "/img/user-10.png",
  service1: "/img/service-1.png",
  service2: "/img/service-2.png",
  service3: "/img/service-3.png",
  service4: "/img/service-4.png",
  logoLight: "/img/logo-light.svg",
  logo: "/img/logo.svg",
  facebook: "/img/facebook.svg",
  twitter: "/img/twitter.svg",
  telegram: "/img/telegram.svg",
  youtube: "/img/youtube.svg",
  vimeo: "/img/vimeo.svg",
  vector: "/img/VectorHIW.svg",
  zgcmq: "/img/zgcmq.svg",
  hero: "/img/hero.png",
  hero2: "/img/hero2.png",
  nft_1: "/img/nft_1.png",
  getAble: "/img/getable.png",
  nft_image_1: "/img/nft-image-1.png",
  nft_image_2: "/img/nft-image-2.png",
  nft_image_3: "/img/nft-image-3.png",
  musiceWave: "/img/musicwave.png",
  update: "/img/update.png",
  earn: "/img/eran.png",
  NFTVideo: "/img/nftvideo.png",
  upload: "/img/upload.png",
  provider1: "/img/provider-1.png",
  provider2: "/img/provider-2.png",
  provider3: "/img/provider-3.png",
  provider4: "/img/provider-4.png",
  founder1: "/img/founder1.jpg",
  founder2: "/img/founder2.jpg",
  founder3: "/img/founder3.jpg",
  founder4: "/img/founder4.jpg",
  loader: "/img/loadergif.gif",
  errorgif: "/img/error.gif",
  transfer: "/img/transfer.gif",
  transferEther: "/img/ethereTransfer.gif",
};

export default images;
